version: '2.0'
services: 
  jenkins:
    image: jenkins/jenkins:2.358
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000  
    volumes:
      - /var/jenkins_home:/var/jenkins_home 
  agent:
    image: jenkins/agent
    restart: always
    ports:
      - "2222:22"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker